// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gygcvvxacmgsxrgqihbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5Z2N2dnhhY21nc3hyZ3FpaGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzA1ODEsImV4cCI6MjA3MjQ0NjU4MX0.OotPH2s3RHB_h_5DplRLA_ut338_VC4ZOSUDm0KIYhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});